services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./:/app
    working_dir: /app/application
    environment:
      - PYTHONPATH=/app


  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    env_file:
      - .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  bot:
    build: .
    container_name: bot
    env_file:
      - .env.bot
    depends_on:
      - postgres
    volumes:
      - ./:/app
    working_dir: /app/bot
    environment:
      - PYTHONPATH=/app
    command: python -u main.py


volumes:
  pgdata:

